import "../blocks/categories/categories.js";
import "../blocks/catalog/catalog.js";
import "../blocks/header/header.js";
import "../blocks/search/search.js";
import "../blocks/slider/slider.js";
import "../blocks/brands/brands.js";
import "../blocks/rating/rating.js";
import "../blocks/filter/filter.js";
import "../blocks/hero/hero.js";